# Generated by Django 4.0.5 on 2022-10-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='chats',
            name='voice_record',
            field=models.FileField(default=1, upload_to='records'),
            preserve_default=False,
        ),
    ]
