# Generated by Django 4.0.5 on 2022-10-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_delete_record_chats_voice_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='sentence_no',
            field=models.IntegerField(default=0),
        ),
    ]
