# Generated by Django 4.0.5 on 2022-10-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chats_sentence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='sentence_no',
            field=models.FloatField(default=0),
        ),
    ]
